### ISSUE TITLE
The score isn't getting updated properly

### ISSUE THREAD

**Issue by mzfr** [acosgames/memorize-up#1]
I'm not sure what the issue is but on my first try I got 8, then in my 2nd I got 10 (the score still shows up as 8 on the leaderboard) and in the 3rd chance I hit 18 but the score still shows up as `8`. The username I used was `itsJstn`.

Then I opened the private window and used the username `mzfr`. In the first chances I got 4 and then in the next I got 15 but if you look at the leaderboard it only shows `mzfr` with 4 points.

So I believe there is some issue in updating the score of the user.

**Comment by acosg** [comment]
You are correct.  I will investigate.  Thanks for reporting.

**Comment by acosg** [comment]
This has been fixed!  It was an issue with the ACOS platform not capturing the room mode correctly to process the leaderboard.
